# This is specifically for Microsoft 365 using DeviceCode Authentication
davmail.server=true
davmail.allowRemote=true # Necessary in Docker for cross-container access
davmail.disableUpdateCheck=true
davmail.logfilepath=/dev/stdout
davmail.ssl.nosecureimap=false
davmail.imapPort=1993
davmail.mode=O365DeviceCode
davmail.enableOAuth2=true
davmail.oauth.tenantId=<replaceme>
davmail.enableOidc=true
davmail.oauth.clientId=<replaceme>
davmail.enableGraph=true
davmail.oauth.scope=openid profile offline_access https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.ReadWrite.Shared https://graph.microsoft.com/User.Read
